# Compile the STM32F10x Standard Peripheral Library
# 3
#Setup cluster
DEVICE_FAMILY = STM32F2XX
DEVICE_TYPE =


#Calculating path
STD_PERIPH_PATH = $(DEVICE_FAMILY)_StdPeriph_Driver

#Job
TARGET_ARCH = -mcpu=cortex-m3 -mthumb -mno-thumb-interwork
TARGET_OPTS = -O2 -finline -finline-functions-called-once
WARNINGS = -Wall -W -Wshadow -Wwrite-strings -Winline
INCLUDE_DIRS = -I . -I ../ -I ./inc/ -I ./inc/$(STD_PERIPH_PATH) 

F_NO_STRICT_ALIASING = -fno-strict-aliasing

DEFINE_LIST = -DUSE_STDPERIPH_DRIVER -D$(DEVICE_FAMILY)_$(DEVICE_TYPE) -DHSE_VALUE=25000000U

COMPILE_OPTS = $(WARNINGS) $(TARGET_ARCH) $(TARGET_OPTS) $(MESSAGES) $(F_NO_STRICT_ALIASING) $(INCLUDE_DIRS) $(DEFINE_LIST) -ffunction-sections

CC = arm-none-eabi-gcc
CFLAGS = $(COMPILE_OPTS)

AS = $(CC) -x assembler-with-cpp -c $(TARGET_ARCH)
ASFLAGS = $(COMPILE_OPTS)

AR = arm-none-eabi-ar
ARFLAGS = cr

LIB_OUT = libstm32fw.a

SOURCES_C = \
 $(wildcard ./src/$(STD_PERIPH_PATH)/*.c) \
 ./src/CMSIS_CM3/system_$(shell echo "$(DEVICE_FAMILY)" | tr A-Z a-z).c \
 ./src/CMSIS_CM3/core_cm3.c 
 
#SOURCES_ASM = \
#  ./src/CMSIS_CM3/asm/startup_stm32f2xx.s

LIB_OBJS = \
  $(patsubst %.c, %.o, $(SOURCES_C))\
  $(patsubst %.s, %.o, $(SOURCES_ASM))
 


.PHONY: all
all: $(LIB_OUT)

$(LIB_OUT): $(LIB_OBJS)
	$(AR) $(ARFLAGS) $@ $(LIB_OBJS)




$(LIB_OBJS): $(wildcard ./inc/CMSIS_CM3/*.h) $(wildcard ./inc/$(STD_PERIPH_PATH)/*.h)

.PHONY: clean
clean:
	-rm -f $(LIB_OBJS) $(LIB_OUT)
